[package]
name = "memo"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["psapi", "processthreadsapi", "handleapi"] }
